apiVersion: apps/v1
kind: Deployment
metadata:
  name: links
  labels: 
    app: links
spec:
  replicas: 1
  selector:
    matchLabels:
      app: links
  template:
    metadata:
      labels:
        app: links
    spec:
      containers:
        - image: links-server:v0.1.1
          name: links
          # This is only informative, the executable decides the ports
          ports:
            - containerPort: 3000
              name: "http"
            - containerPort: 8081
              name: "metrics"
          env:
            - name: RUST_LOG
              valueFrom:
                configMapKeyRef:
                  name: links
                  key: rust_log_level
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          hostPath: 
            path: /gazda/links
            type: Directory


